logLevel: info
logDestinations: [stdout]
readTimeout: 10s
writeTimeout: 10s
api: yes
apiAddress: :9997
metrics: yes
metricsAddress: :9998
rtsp: yes
rtspAddress: :8554
rtspEncryption: "no"
rtspAuthMethods: [basic]
hls: yes
hlsAddress: :8888
hlsVariant: fmp4
hlsSegmentDuration: 2s
hlsPartDuration: 200ms
hlsSegmentCount: 3
hlsAlwaysRemux: yes
webrtc: yes
webrtcAddress: :8889
playback: yes
playbackAddress: :9996
rtmp: no
srt: no
authMethod: internal
authInternalUsers:
  - user: admin
    pass: admin
    permissions:
      - action: publish
        path: ""
      - action: read
        path: ""
      - action: playback
        path: ""
      - action: api
  - user: publisher
    pass: publisher_secret
    permissions:
      - action: publish
        path: ""
  - user: any
    pass: ""
    permissions:
      - action: read
        path: ""
      - action: playback
        path: ""
paths:
  all:
    source: publisher
    recordPath: ./recordings/%path/%Y-%m-%d_%H-%M-%S-%f
    recordFormat: fmp4
    recordDeleteAfter: 720h0m0s
    recordSegmentDuration: 1h0m0s
    runOnRecordSegmentCreate: /on-record-segment.sh recording_start
    runOnRecordSegmentComplete: /on-record-segment.sh recording_end
